//! # Contact Message Model
//!
//! ## Purpose
//! Represents contact form submissions from website visitors.
//! Stores inquiries, questions, and feedback for follow-up.
//!
//! ## Database Table: `contact_messages`
//! - Primary key: `id` (serial)
//! - Status: "new", "read", "responded", "archived"
//! - Used for: Customer support, sales inquiries, feedback
//!
//! ## Relation to Entire Program
//! - **Created By**: ContactRepository::create() via contact form submission
//! - **Used By**: Admin dashboard (future), email notifications
//! - **Future**: Will link to CRM system, auto-responder emails

use chrono::{DateTime, Utc};         // Timestamps
use serde::{Deserialize, Serialize}; // JSON serialization

/// Contact message entity - matches `contact_messages` table in database
/// Represents a message sent through the website contact form
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ContactMessage {
    /// Unique message ID (auto-generated by database)
    pub id: i32,
    /// Sender's name
    pub name: String,
    /// Sender's email (for follow-up)
    pub email: String,
    /// Message content
    pub message: String,
    /// Message status (new, read, responded, archived)
    pub status: String,
    /// Message submission timestamp
    pub created_at: DateTime<Utc>,
}

/// DTO for creating a new contact message
/// Received from: POST /api/contact request (contact form)
#[derive(Debug, Clone, Deserialize)]
pub struct NewContactMessage {
    /// Sender's name from form
    pub name: String,
    /// Sender's email from form
    pub email: String,
    /// Message text from textarea
    pub message: String,
}
