//! # Customer Model
//!
//! ## Purpose
//! Represents customers who request handyman services.
//! Stores contact information for booking follow-up.
//!
//! ## Database Table: `customers`
//! - Primary key: `id` (serial)
//! - Unique: `email`
//! - Used for: Service bookings, contact info, notifications
//!
//! ## Relation to Entire Program
//! - **Created By**: CustomerRepository::create_or_get() when booking is made
//! - **Used By**: Booking creation (links customer to booking)
//! - **Relations**: Customer has many bookings
//! - **Smart Logic**: Prevents duplicate customers with same email

use chrono::{DateTime, Utc};         // Timestamps
use serde::{Deserialize, Serialize}; // JSON serialization

/// Customer entity - matches `customers` table in database
/// Represents someone who requests handyman services
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Customer {
    /// Unique customer ID (auto-generated by database)
    pub id: i32,
    /// Customer's full name
    pub full_name: String,
    /// Customer's email (unique - used to prevent duplicates)
    pub email: String,
    /// Optional phone number
    pub phone: Option<String>,
    /// Account creation timestamp
    pub created_at: DateTime<Utc>,
    /// Last update timestamp
    pub updated_at: DateTime<Utc>,
}

/// DTO for creating a new customer
/// Received from: Booking form submission
#[derive(Debug, Clone, Deserialize)]
pub struct NewCustomer {
    /// Full name from booking form
    pub full_name: String,
    /// Email from booking form (checked for existing customer)
    pub email: String,
    /// Optional phone number from booking form
    pub phone: Option<String>,
}

impl NewCustomer {
    /// Create a new customer DTO
    /// Called by: Booking handler when processing form submission
    pub fn new(full_name: String, email: String, phone: Option<String>) -> Self {
        Self {
            full_name,
            email,
            phone,
        }
    }
}
